"""initial_schema

Revision ID: f4acf49956f4
Revises:
Create Date: 2026-06-07 13:45:27.665463

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f4acf49956f4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_accounts",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("balance_cents", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("fulfillment_kind", sa.String(length=40), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("stars_amount", sa.Integer(), nullable=True),
        sa.Column("ton_amount_nano", sa.Numeric(precision=78, scale=0), nullable=True),
        sa.Column("credit_cents", sa.Integer(), nullable=False),
        sa.Column("service_minutes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_table(
        "user_wallets",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("ton_address", sa.String(length=120), nullable=False),
        sa.Column("wallet_app", sa.String(length=64), nullable=True),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("expected_currency", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_product_id"), "orders", ["product_id"], unique=False)
    op.create_index(op.f("ix_orders_provider"), "orders", ["provider"], unique=False)
    op.create_index(op.f("ix_orders_sku"), "orders", ["sku"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_orders_telegram_user_id"), "orders", ["telegram_user_id"], unique=False
    )
    op.create_table(
        "credit_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("balance_after_cents", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("external_ref", sa.String(length=220), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("direction IN ('credit', 'debit')", name="ck_credit_direction"),
        sa.CheckConstraint("amount_cents > 0", name="ck_credit_amount_positive"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_ref"),
    )
    op.create_index(op.f("ix_credit_ledger_order_id"), "credit_ledger", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_credit_ledger_telegram_user_id"),
        "credit_ledger",
        ["telegram_user_id"],
        unique=False,
    )
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_ref", sa.String(length=220), nullable=False),
        sa.Column("amount", sa.Numeric(precision=78, scale=0), nullable=False),
        sa.Column("currency", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_ref", name="uq_payment_provider_ref"),
    )
    op.create_index(
        op.f("ix_payment_attempts_order_id"), "payment_attempts", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_attempts_provider"), "payment_attempts", ["provider"], unique=False
    )
    op.create_table(
        "token_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("token_kind", sa.String(length=40), nullable=False),
        sa.Column("service_minutes", sa.Integer(), nullable=False),
        sa.Column("recipient_wallet", sa.String(length=120), nullable=True),
        sa.Column("mint_status", sa.String(length=40), nullable=False),
        sa.Column("token_ref", sa.String(length=220), nullable=True),
        sa.Column("mint_tx_hash", sa.String(length=220), nullable=True),
        sa.Column("redeem_status", sa.String(length=40), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("minted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_grants_order_id"), "token_grants", ["order_id"], unique=True)
    op.create_index(
        op.f("ix_token_grants_telegram_user_id"), "token_grants", ["telegram_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_grants_telegram_user_id"), table_name="token_grants")
    op.drop_index(op.f("ix_token_grants_order_id"), table_name="token_grants")
    op.drop_table("token_grants")
    op.drop_index(op.f("ix_payment_attempts_provider"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_order_id"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index(op.f("ix_credit_ledger_telegram_user_id"), table_name="credit_ledger")
    op.drop_index(op.f("ix_credit_ledger_order_id"), table_name="credit_ledger")
    op.drop_table("credit_ledger")
    op.drop_index(op.f("ix_orders_telegram_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_sku"), table_name="orders")
    op.drop_index(op.f("ix_orders_provider"), table_name="orders")
    op.drop_index(op.f("ix_orders_product_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("user_wallets")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_table("products")
    op.drop_table("credit_accounts")
    # ### end Alembic commands ###
